from alembic import command
from alembic.script import ScriptDirectory
from sqlalchemy import create_engine, inspect, text

from app.db_migrate import BASELINE_REVISION, alembic_config, upgrade_database


def _head(config):
    return ScriptDirectory.from_config(config).get_current_head()


def test_migrated_schema_matches_models(database_url):
    # alembic check raises AutogenerateDiffsDetected when models and migrations disagree.
    command.check(alembic_config(database_url))


def test_empty_database_is_migrated_to_head(empty_database_url):
    upgrade_database(empty_database_url)
    config = alembic_config(empty_database_url)
    engine = create_engine(empty_database_url)
    try:
        with engine.connect() as connection:
            assert connection.execute(text('select version_num from alembic_version')).scalar_one() == _head(config)
    finally:
        engine.dispose()
    command.check(config)


def test_downgrade_to_base_and_upgrade_again(database_url):
    config = alembic_config(database_url)
    command.downgrade(config, 'base')
    engine = create_engine(database_url)
    try:
        assert set(inspect(engine).get_table_names()) == {'alembic_version'}
    finally:
        engine.dispose()
    command.upgrade(config, 'head')
    command.check(config)


def test_database_created_before_migrations_keeps_its_data(empty_database_url):
    config = alembic_config(empty_database_url)
    # Recreate the pre-migration state: baseline tables with data but no alembic_version table.
    command.upgrade(config, BASELINE_REVISION)
    engine = create_engine(empty_database_url)
    try:
        with engine.begin() as connection:
            connection.execute(text('drop table alembic_version'))
            connection.execute(text("insert into universities (name, city, contact) values ('Вуз', 'Москва', '')"))

        upgrade_database(empty_database_url)

        with engine.connect() as connection:
            assert connection.execute(text('select version_num from alembic_version')).scalar_one() == _head(config)
            assert connection.execute(text('select count(*) from universities')).scalar_one() == 1
    finally:
        engine.dispose()
    command.check(config)
