import os
import subprocess
import sys

from alembic import command
from alembic.script import ScriptDirectory
from sqlalchemy import create_engine, inspect, text

from app.db_migrate import BACKEND_DIR, BASELINE_REVISION, alembic_config, upgrade_database


def _head(config):
    return ScriptDirectory.from_config(config).get_current_head()


def test_migrated_schema_matches_models(database_url):
    # alembic check raises AutogenerateDiffsDetected when models and migrations disagree.
    command.check(alembic_config(database_url))


def test_empty_database_is_migrated_to_head(empty_database_url):
    upgrade_database(empty_database_url)
    config = alembic_config(empty_database_url)
    engine = create_engine(empty_database_url)
    try:
        with engine.connect() as connection:
            assert connection.execute(text('select version_num from alembic_version')).scalar_one() == _head(config)
    finally:
        engine.dispose()
    command.check(config)


def test_downgrade_to_base_and_upgrade_again(database_url):
    config = alembic_config(database_url)
    command.downgrade(config, 'base')
    engine = create_engine(database_url)
    try:
        assert set(inspect(engine).get_table_names()) == {'alembic_version'}
    finally:
        engine.dispose()
    command.upgrade(config, 'head')
    command.check(config)


def test_alembic_command_line_needs_only_database_url(database_url):
    # The real CLI goes through migrations/env.py; login settings must not be required for schema work.
    environment = {key: value for key, value in os.environ.items() if not key.startswith(('OIDC_', 'SESSION_', 'PUBLIC_BASE_URL'))}
    environment['DATABASE_URL'] = database_url
    result = subprocess.run(
        [sys.executable, '-m', 'alembic', 'current'],
        cwd=BACKEND_DIR, env=environment, capture_output=True, text=True, timeout=60,
    )
    assert result.returncode == 0, result.stderr
    assert '(head)' in result.stdout


def test_database_created_before_migrations_keeps_its_data(empty_database_url):
    config = alembic_config(empty_database_url)
    # Recreate the pre-migration state: baseline tables with data but no alembic_version table.
    command.upgrade(config, BASELINE_REVISION)
    engine = create_engine(empty_database_url)
    try:
        with engine.begin() as connection:
            connection.execute(text('drop table alembic_version'))
            connection.execute(text("insert into universities (name, city, contact) values ('Вуз', 'Москва', '')"))

        upgrade_database(empty_database_url)

        with engine.connect() as connection:
            assert connection.execute(text('select version_num from alembic_version')).scalar_one() == _head(config)
            assert connection.execute(text('select count(*) from universities')).scalar_one() == 1
    finally:
        engine.dispose()
    command.check(config)
